#pragma config(Sensor, in1,    Yaw,            sensorGyro)
#pragma config(Sensor, in2,    BallLight,      sensorReflection)
#pragma config(Sensor, dgtl1,  FlyWheel,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftE,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rightE,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  flySwitch,      sensorTouch)
#pragma config(Motor,  port1,           Seymore,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftDrive1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftDrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Fly1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Fly2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Fly3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Fly4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RightDrive2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RightDrive1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          FeedMe,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LeftSpeed = 0;
int RightSpeed = 0;
int Flyspeed = 0;
int Error = 0;
int n = 0;
int TargetSpeed[5] = {0, 114, 135, 142, 170};
int stillspeed = 50;
TVexJoysticks buttons[5] = {Btn8D, Btn7U, Btn7R, Btn7D, Btn7L};
int DeltaE = 0;
long Integral = 0;
int PIDPower = 0;
float Ki[5] = {0, 0.001, 0.001, 0.001, 0.001};
float KiIntegral = 0;
float Kp[5] = {0, 4.2, 4.2, 4.2, 4.2};
float KpError = 0;
float Kd[5] = {0, 9.2, 9.2, 9.2, 9.2};
float KdDeltaE = 0;
float PowerLevel = 1;
int PrevError = 0;
int AccError[5]  = {-1, 400, 3, 4, 15};
float ErrorMargin = 0.1;
int BangBang = 0;
float AdjPID = 0;
int PIBang = 0;
int MeterSpeed = 0;
int AutoSpeed = 0;
int SeymoreSpeed = 0;
int BallThreshold = 300;
int FeedSpeed = 100;
float AccErrorMargin = 0;

void Motorspeeds()
{
	motor[LeftDrive1] = LeftSpeed;
	motor[LeftDrive2] = LeftSpeed;
	motor[RightDrive1] = RightSpeed;
	motor[RightDrive2] = RightSpeed;
	motor[Fly1] = Flyspeed;
	motor[Fly2] = Flyspeed;
	motor[Fly3] = Flyspeed;
	motor[Fly4] = Flyspeed;
	motor[Seymore] = SeymoreSpeed;
	motor[FeedMe] = vexRT[Btn6U]*127 + vexRT[Btn6D]*-127;
}

void MechSeymore()
{
	AutoSpeed = SensorValue[BallLight]>BallThreshold&&SensorValue[flySwitch]==0?FeedSpeed:0;
	MeterSpeed = SensorValue[flySwitch]==1&&Error>AccError[n]?0:127*vexRT[Btn5U]-127*vexRT[Btn5D];
	SeymoreSpeed = vexRT[Btn5U]==1||vexRT[Btn5D]==1?MeterSpeed:AutoSpeed;
}

task Flywheel()
{
	while(true)
	{
		SensorValue[FlyWheel] = 0;
		wait1Msec(15);
		Error = TargetSpeed[n] - abs(SensorValue[FlyWheel]);
		KpError = Kp*Error;
		Integral += (Error + PrevError)/2;
		KiIntegral = Ki*Integral;
		DeltaE = PrevError - Error;
		KdDeltaE = Kd*DeltaE;
		PIDPower = KpError + KiIntegral + KdDeltaE;
		PowerLevel = 8100/nImmediateBatteryLevel;
		AdjPID = PowerLevel*PIDPower;
		BangBang = Error > 0 ? 127 : stillspeed;
		AccErrorMargin = n==0?0:abs(Error)/TargetSpeed[n];
		PIBang = AccErrorMargin > ErrorMargin ? BangBang : AdjPID;
		Flyspeed = abs(PIBang*(n==0?0:1));
	}
}

task main()
{
	startTask(Flywheel);
	while(true)
	{
		Motorspeeds();
		MechSeymore();
		LeftSpeed = vexRT[Ch3];
		RightSpeed = vexRT[Ch2];
		for(int i = 0; i<5; i++)
		{
			n = vexRT[buttons[i]] == 1 ? i : n;
		}
	}
}
