#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  FlySpin,        sensorQuadEncoder)
#pragma config(Sensor, dgtl11, T,              sensorTouch)
#pragma config(Sensor, dgtl12, ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           feed,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Left2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BLeft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FRight,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           BRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          intake,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  port,          lift2,         tmotorVex393_HBridge, openLoop, reversed)

int step = 0;
int Power = 0;
float PowerPercentLeft;
float PowerPercentRight;
float MotorLeftPower = 127;
float MotorRightPower = 127;
float RightSpeed;
float LeftSpeed;
float LastLeftMotorValue;
float LastRightMotorValue;
int FullPower = 100;
int SmallPower = 85;
int SetPower;
int HammerPower = -85;
int PowerStep = 1;
int Speed;
int NormalSpeed;
int LastSpeed;
int FullNormal = 8;
int SmallNormal = 6;

task Drive()
{
	while(1==1)
	{
		PowerPercentRight = ((vexRT[Ch2] * 100)/127);
		PowerPercentLeft = ((vexRT[Ch3] * 100)/127);
		motor[Right1] = (MotorRightPower * PowerPercentRight/100);
		motor[Left1] = (MotorLeftPower * PowerPercentLeft/100);
		motor[Right2] = (MotorRightPower * PowerPercentRight/100);
		motor[Left2] = (MotorLeftPower * PowerPercentLeft/100);
		do
		{
			RightSpeed = (SensorValue[RightEncoder] - LastRightMotorValue);
			LeftSpeed = (SensorValue[LeftEncoder] - LastLeftMotorValue);
			LastRightMotorValue = SensorValue[RightEncoder];
			LastLeftMotorValue = SensorValue[LeftEncoder];
			wait1Msec(250);
		}
		while(1==1);
		if((RightSpeed/PowerPercentRight) > (LeftSpeed/PowerPercentLeft))
		{
			if (MotorLeftPower < 127)
			{
				MotorLeftPower = (MotorLeftPower + 1);
			}
			else
			{
				MotorRightPower = (MotorRightPower - 1);
			}
		}
		else if((RightSpeed/PowerPercentRight) < (LeftSpeed/PowerPercentLeft))
		{
			if (MotorRightPower < 127)
			{
				MotorRightPower = (MotorRightPower + 1);
			}
			else
			{
				MotorLeftPower = MotorLeftPower - 1;
			}
		}
	}
}

task Flywheel()
{
	while(true)
	{
		if (vexRT[Btn7D] == 1 && step == 0)
  	{
  		step = 1;
  	}
  	if (vexRT[Btn7D] == 1 && step == 3)
  	{
  		step = 2;
  	}
  	if (vexRT[Btn7D] == 0 && step == 1)
  	{
  		step = 3;
  	}
  	if (vexRT[Btn7D] == 0 && step == 2)
  	{
  		step = 0;
  	}
  	if (step == 1 || step == 3)
  	{
  		motor[FLeft] = Power;
  		motor[FRight] = Power;
  		motor[BLeft] = Power;
  		motor[BRight] = Power;
  		if(PowerStep == 1)
  		{
	  		if(Power < (SetPower/3))
 		 		{
 	 				Power = Power + 1;
  				wait1Msec(5);
  			}
  			else if(Power < (SetPower *(2/3)))
  			{
  				Power = Power + 1;
  				wait1Msec(3);
  			}
  			else if(Power < SetPower)
  			{
  				Power = Power + 1;
  				wait1Msec(1);
  			}
  			if(Power == SetPower)
  			{
  				PowerStep = 0;
  			}
  		}
  		else if(PowerStep == 0)
  		{
  			if(Speed < NormalSpeed)
  			{
  				Power = SetPower + 27;
  			}
  			else
  			{
  				Power = SetPower;
  			}
  		}
  	}
  	else if(vexRT[Btn8D] == 1)
  	{
  		motor[FLeft] = HammerPower;
  		motor[FRight] = HammerPower;
  		motor[BLeft] = HammerPower;
  		motor[BRight] = HammerPower;
  	}
  	else if(step == 0 || step == 2)
  	{
  		motor[FLeft] = 0;
  		motor[FRight] = 0;
  		motor[BLeft] = 0;
  		motor[BRight] = 0;
  		Power = 0;
  		PowerStep = 1;
  	}
  }
}
task FeedIntake()
{
	while(true)
  {
  	if (vexRT[Btn6U] == 1)
  	{
  		motor[intake] = 127;
  	}
  	else if(vexRT[Btn6D] == 1)
  	{
  		motor[intake] = -127;
  	}
  	else
  	{
  		motor[intake] = 0;
  	}
  	if(SensorValue[T] == 1)
  	{
  		motor[feed] = 127;
  	}
  	else if(vexRT[Btn5D] == 1)
  	{
  		motor[feed] = -127;
  	}
  	else
  	{
  		motor[feed] = 0;
  	}
  }
}

task flyspeed()
{
	while(true)
	{
		Speed = abs(SensorValue[FlySpin] - LastSpeed);
		LastSpeed = SensorValue[FlySpin];
		wait1Msec(10);
	}
}

task main()
{
  while(true)
  {
  	startTask(Drive);
  	startTask(FeedIntake);
  	startTask(Flywheel);
  	startTask(flyspeed);
  	if (vexRT[Btn7R] == 1)
  	{
  		SetPower = FullPower;
  		NormalSpeed = FullNormal;
  	}
  	else if (vexRT[Btn7L] == 1)
  	{
  		SetPower = SmallPower;
  		NormalSpeed = SmallNormal;
  	}
  }
}
